# -*- coding: utf-8 -*-
"""All UI strings, bilingual. UI[lang] is passed to templates as `T`. Keep keys in sync across langs.
MODELS = the model names shown on the answer cards (single = 1 name, multi = all 5)."""

MODELS = ["ChatGPT", "Gemini", "Claude", "MAI", "DeepSeek"]

UI = {
    "en": {
        "next": "Continue",
        "back": "Back to previous page",
        "consent_title": "Making sense of AI assistants' answers",
        "consent_p1": "<b>What this study is about.</b> This study is run by a research team at The Hong Kong University of Science and Technology (Guangzhou), led by Weikai Yang (weikaiyang@hkust-gz.edu.cn). It looks at how people read and judge answers given by AI assistants when a request could be understood in more than one way. Ethics approval: HAREC protocol no. [to be assigned upon approval].",
        "consent_p2": "<b>What you will do.</b> The session takes about 10 minutes in your browser. After a short instruction page, one worked example and one comprehension question, you will see 14 short workplace situations. For each one an AI assistant has produced an answer; you decide whether the answer has enough information to be used as it is, or whether important information is missing, and you rate from 1 to 5 stars how confident you are that the answer itself is correct. If you judge that something is missing, you also pick the one point you would clarify. Two short background questions follow. <b>Some details about the exact purpose are held back so that your responses stay natural; they are explained in full on the last page.</b>",
        "consent_p3": "<b>Risks.</b> There are no risks beyond those of ordinary computer use. The tasks are short and contain nothing sensitive or personal.",
        "consent_p4": "<b>Benefits.</b> There is no direct benefit to you. Your responses help research on how people work with AI tools, and the last page explains the problem this study is about.",
        "consent_p5": "<b>Compensation.</b> There is no payment or reward of any kind for taking part.",
        "consent_p6": "<b>Voluntary participation.</b> Taking part is entirely voluntary. You may stop at any time by closing the window, without giving a reason. Nothing happens if you stop, and you do not need to tell anyone.",
        "consent_p7": "<b>Privacy and data.</b> We do not collect your name, contact details, network address or location. The only things recorded are an automatically generated anonymous code, your answers, and how long each page took. The data cannot be linked back to you. They are analysed only in aggregate, and an anonymous version may be published alongside the research. Because nothing identifying is recorded, responses cannot be withdrawn once they have been submitted.",
        "consent_p8": "<b>No obligation.</b> Nobody is required to take part. Your decision will not affect your studies, your work, your grades, or your relationship with the researchers. The researchers cannot tell who has taken part and who has not.",
        "consent_agree": "I have read and understood the above. I understand that some details about the study's purpose are withheld until the end. I am 18 years of age or older. I agree to take part.",
        "consent_contact": "Questions? Contact Weikai Yang (weikaiyang@hkust-gz.edu.cn). For questions about your rights as a research participant, contact the HKUST(GZ) Human and Artefacts Research Ethics Committee (HAREC).",
        "instr_title": "What you'll do",
        "instr_p1": "Imagine you are at work. For each of 14 short tasks, a coworker asks for something and an <b>AI assistant</b> gives an answer.",
        "instr_multi": "For some tasks you'll see the answer from <b>one</b> AI model; for others, <b>five</b> different AI models were each asked and all five gave the same answer.",
        "instr_data": "Some scenarios refer to an attached table or a system record. Assume that source was available to the AI; you do not need to recalculate the displayed number. Judge whether the request and the AI answer provide enough information for the answer to be used.",
        "instr_p2": "Your only job each time is to decide <b>one thing</b>:",
        "instr_opt1": "<b>✅ The answer is ready to use</b> — nothing important is left unclear.",
        "instr_opt2": "<b>⚠️ Important information is missing</b> — you'd need to clarify something before trusting it.",
        "instr_p3": "If you choose “missing,” we'll ask which one thing you would clarify. Then you rate your confidence in the displayed AI answer itself — not your confidence in your own choice or in the clarifying question. That's it — let's try one example first.",
        "we_title": "Example (not scored)",
        "we_scenario": "A coworker says: “Book a meeting room for the team next Friday at 10.”",
        "we_task": "Book the room.",
        "we_answer": "Booked Room A for next Friday at 10 AM.",
        "we_explain": "The AI <b>assumed</b> 10 in the morning — but the request only said “10,” never morning or evening. When a needed detail like that is missing, the answer might be wrong, and you'd clarify first. When nothing important is missing, the answer is fine to use as-is.",
        "we_ready": "Ready — you'll now do 14 short tasks. <b>Some answers will be fine to use as-is; others may be missing a needed detail.</b> Read each one and decide.",
        "comp_title": "Quick check",
        "comp_q": "In each task, your job is to decide:",
        "comp_o0": "Whether the answer is written politely",
        "comp_o1": "Whether the answer is ready to use, or important information is missing",
        "comp_o2": "How quickly the AI responded",
        "comp_err": "Not quite — please re-read the short instructions and try again.",
        "trial_progress": "Task {n} of {total}",
        "clarify_progress": "Follow-up for task {n} of {total}",
        "lbl_scenario": "The situation",
        "lbl_task": "What's being asked",
        "lbl_sep": " — ",
        "lbl_answer_single": "1 AI model was asked:",
        "lbl_answer_multi": "5 AI models were asked — all 5 gave the same answer:",
        "banner_fake": "ℹ️ Five different AI models were each asked, and all five gave this answer.",
        "banner_dep": "ℹ️ All five models were sent the <b>same prompt</b>, and that prompt did not specify one needed detail — each model filled that gap on its own.",
        "q1": "Is this answer ready to use, or is important information missing?",
        "a_accept": "✅ The answer has enough information and can be used",
        "a_flag": "⚠️ Important information is missing — I'd clarify first",
        "gap_q": "You said something's missing. What is the <b>most important</b> thing to clarify?",
        "other_option": "Other",
        "conf_q": "How confident are you that the displayed AI answer itself is correct and ready to use?",
        "conf_star_hint": "(1 star = not at all sure, 5 stars = completely sure)",
        "err_need_choice": "Please choose one option above to continue.",
        "err_need_gap": "Please pick the most important thing to clarify.",
        "err_need_conf": "Please give a star rating.",
        "confirm_decision": "Confirm decision",
        "submit_clarification": "Submit clarification",
        "readonly_back": "View previous page (read-only)",
        "readonly_previous": "View previous task (read-only)",
        "hide_review": "Hide read-only review",
        "review_title": "Previously submitted answer — read-only",
        "review_source": "AI source",
        "review_single": "One AI model",
        "review_multi": "Five AI models gave the same answer",
        "review_decision": "Your submitted decision",
        "review_confidence": "Your submitted confidence",
        "attn_title": "Attention check",
        "attn_q": "To show you are reading, please choose <b>Disagree</b> below.",
        "attn_a1": "Agree",
        "attn_a0": "Disagree",
        "attn_a2": "Neutral",
        "demo_title": "A few last questions",
        "demo_age": "Your age group",
        "age_groups": [
            "Under 18",
            "18–24",
            "25–34",
            "35–44",
            "45–54",
            "55–64",
            "65+"
        ],
        "demo_ai_q": "How often do you use AI assistants (e.g., ChatGPT)?",
        "demo_ai": [
            "Never",
            "Rarely",
            "Sometimes",
            "Often",
            "Daily"
        ],
        "debrief_title": "Thank you — what this study was really about",
        "debrief_p1": "The AI answers, and especially the <b>“5 of 5 AI models agree”</b> displays, were <b>examples created by the researchers</b> — not live outputs from real models. Nine tasks were deliberately left underspecified by omitting one needed detail; five comparison tasks provided the needed detail and had answers that were ready to use.",
        "debrief_p2": "We study whether a unanimous “models agree” display makes people more likely to accept an answer and feel more confident, and whether telling people the answers are not independent helps. Different people saw the same tasks with different displays, so we can compare fairly.",
        "finish": "Submit and finish"
    },
    "zh": {
        "next": "继续",
        "back": "返回上一页",
        "consent_title": "看懂 AI 助手的回答",
        "consent_p1": "<b>本研究是什么。</b>本研究由香港科技大学（广州）的研究团队开展，负责人为 Weikai Yang（weikaiyang@hkust-gz.edu.cn）。研究关注：当一个请求可能有多种理解方式时，人们如何阅读和判断 AI 助手给出的回答。伦理批准：HAREC 编号【获批后填入】。",
        "consent_p2": "<b>您要做什么。</b>整个过程约 10 分钟，在浏览器中完成。先是一页说明、一道示范题和一道理解检查，然后是 14 个简短的工作场景。每个场景中 AI 助手给出了一个回答，您判断这个回答的信息是否足够、可以直接使用，还是缺了重要信息；并用 1 到 5 星评价您有多确信这个回答本身是正确的。若您认为缺了信息，还会请您选出最需要澄清的一点。最后是两道背景问题。<b>为了让您的反应保持自然，研究的确切目的有一部分暂时不告知，会在最后一页完整说明。</b>",
        "consent_p3": "<b>风险。</b>除普通上网外没有任何风险。题目都很简短，不涉及任何敏感或私人内容。",
        "consent_p4": "<b>获益。</b>参与本研究对您没有直接好处。您的回答有助于研究人们如何使用 AI 工具；最后一页会说明本研究关注的问题。",
        "consent_p5": "<b>报酬。</b>参与本研究没有任何形式的报酬或奖励。",
        "consent_p6": "<b>自愿参与。</b>参与完全自愿。您可以随时关闭窗口退出，无需说明理由。退出不会有任何后果，也不需要告知任何人。",
        "consent_p7": "<b>隐私与数据。</b>我们不收集您的姓名、联系方式、网络地址或位置。仅记录系统自动生成的匿名编号、您的作答，以及每页停留的时长。这些数据无法追溯到您本人。数据只作汇总分析，匿名版本可能随研究成果一并公开。由于不记录任何身份信息，回答一经提交便无法撤回。",
        "consent_p8": "<b>无强制。</b>没有人有义务参加。您的决定不会影响您的学业、工作、成绩，也不会影响您与研究者的关系。研究者无法知道谁参加了、谁没有参加。",
        "consent_agree": "我已阅读并理解上述内容。我理解研究目的有一部分暂时不告知，会在结束时说明。我已年满 18 周岁。我同意参与。",
        "consent_contact": "如有疑问，请联系 Weikai Yang（weikaiyang@hkust-gz.edu.cn）。如对作为研究参与者的权利有疑问，请联系香港科技大学（广州）人类与人工物研究伦理委员会（HAREC）。",
        "instr_title": "您要做什么",
        "instr_p1": "想象您在上班。在 14 个短任务中，同事提出一个请求，一个 <b>AI 助手</b> 给出回答。",
        "instr_multi": "有的题您会看到<b>一个</b> AI 模型的回答；有的题是<b>五个</b>不同的 AI 模型各自作答，五个都给出了同一个答案。",
        "instr_data": "部分情境会提到附件表格或系统记录。请假设 AI 可以使用这些数据来源；您不需要重新计算屏幕上的数字。您只需判断请求与 AI 回答提供的信息是否足以让该回答直接使用。",
        "instr_p2": "每次您只需判断<b>一件事</b>：",
        "instr_opt1": "<b>✅ 这个回答可以直接用</b>——没有重要的地方含糊不清。",
        "instr_opt2": "<b>⚠️ 缺了重要信息</b>——您得先澄清某个点才能信任它。",
        "instr_p3": "如果选“缺信息”，我们会问您最想澄清哪一点。然后请评价您对屏幕上 AI 回答本身的信心，而不是对自己所选答案或澄清问题的信心。就这些——先试一个例子。",
        "we_title": "示范题（不计分）",
        "we_scenario": "同事说：“帮团队订下周五 10 点的会议室。”",
        "we_task": "订会议室。",
        "we_answer": "已订下周五上午 10:00 的 A 会议室。",
        "we_explain": "AI <b>默认</b>了上午，但请求只说了“10 点”，没说上午还是晚上。当这样一个需要的细节缺失时，回答可能是错的，您会先去澄清；而当没有重要信息缺失时，回答就可以直接用。",
        "we_ready": "准备好了——接下来您会做 14 个短任务。<b>有的回答可以直接用，有的可能缺了一个需要的细节。</b>认真读每一题再判断。",
        "comp_title": "小测一下",
        "comp_q": "在每个任务中，您的任务是判断：",
        "comp_o0": "回答写得礼不礼貌",
        "comp_o1": "回答可不可以直接用，还是缺了重要信息",
        "comp_o2": "AI 回应有多快",
        "comp_err": "不太对——请重读一下说明再试。",
        "trial_progress": "第 {n} / {total} 题",
        "clarify_progress": "第 {n} / {total} 题的后续问题",
        "lbl_scenario": "情境",
        "lbl_task": "要求",
        "lbl_sep": "：",
        "lbl_answer_single": "询问了 1 个 AI 模型：",
        "lbl_answer_multi": "询问了 5 个 AI 模型——5 个都给出了同一个答案：",
        "banner_fake": "ℹ️ 我们分别询问了五个不同的 AI 模型，五个都给出了这个答案。",
        "banner_dep": "ℹ️ 五个模型收到的是<b>同一条 prompt</b>，而这条 prompt 没有说清其中一个需要的细节——五个模型各自把这个空填上了。",
        "q1": "这个回答可以直接用，还是缺了重要信息？",
        "a_accept": "✅ 这个回答信息足够，可以直接用",
        "a_flag": "⚠️ 缺了重要信息——我会先去澄清",
        "gap_q": "您说缺了东西。<b>最需要</b>先澄清的是哪一点？",
        "other_option": "其他",
        "conf_q": "您有多确信屏幕上显示的 AI 回答本身是正确的、可以直接使用？",
        "conf_star_hint": "（1 星 = 完全不确信，5 星 = 完全确信）",
        "err_need_choice": "请先选择上面一项再继续。",
        "err_need_gap": "请选出最需要澄清的一点。",
        "err_need_conf": "请给出星级评分。",
        "confirm_decision": "确认判断",
        "submit_clarification": "提交澄清选择",
        "readonly_back": "查看上一页（只读）",
        "readonly_previous": "查看上一题（只读）",
        "hide_review": "收起只读内容",
        "review_title": "已提交的回答（只读，不能修改）",
        "review_source": "AI 来源",
        "review_single": "1 个 AI 模型",
        "review_multi": "5 个 AI 模型给出了同一答案",
        "review_decision": "您已提交的判断",
        "review_confidence": "您已提交的信心",
        "attn_title": "注意力检查",
        "attn_q": "为表明您在认真阅读，请选择下面的<b>不同意</b>。",
        "attn_a1": "同意",
        "attn_a0": "不同意",
        "attn_a2": "中立",
        "demo_title": "最后几个问题",
        "demo_age": "您的年龄段",
        "age_groups": [
            "18 岁以下",
            "18–24",
            "25–34",
            "35–44",
            "45–54",
            "55–64",
            "65 岁以上"
        ],
        "demo_ai_q": "您多常使用 AI 助手（如 ChatGPT）？",
        "demo_ai": [
            "从不",
            "很少",
            "有时",
            "经常",
            "每天"
        ],
        "debrief_title": "谢谢——这项研究的真正目的",
        "debrief_p1": "这些 AI 回答，尤其是<b>“5 个 AI 模型中 5 个一致”</b>的显示，都是<b>研究者构造的示例</b>——并非真实模型的实时输出。其中 9 道题故意省略了一个作出判断所需的细节；另外 5 道对照题已经给出了所需信息，其回答可以直接使用。",
        "debrief_p2": "我们研究：“多模型一致”的显示是否会让人更容易接受答案、更有把握；以及告知“这些答案并不独立”是否有帮助。不同的人看到的是同样题目的不同显示，以便公平比较。",
        "finish": "提交并结束"
    }
}

assert set(UI["en"].keys()) == set(UI["zh"].keys()), "en/zh UI keys out of sync"
