# -*- coding: utf-8 -*-
"""All UI strings, bilingual. UI[lang] is passed to templates as `T`. Keep keys in sync across langs.
MODELS = the model names shown on the answer cards (single = 1 name, multi = all 5)."""

MODELS = ["ChatGPT", "Gemini", "Claude", "Copilot", "DeepSeek"]

UI = {
    "en": {
        "next": "Continue",
        "consent_title": "Making sense of AI assistants' answers",
        "consent_p1": "You are invited to a short (about 10 minute) study about how people read answers from AI assistants. You will look at 14 short work situations and, for each, make one quick decision and one rating.",
        "consent_p2": "Some details about the study's exact purpose are held back so your answers stay natural; they will be fully explained at the end. There are no risks beyond ordinary computer use. Participation is voluntary and anonymous; you can stop anytime by closing the window. You will be paid on completion.",
        "consent_agree": "I have read the above and I agree to take part.",
        "instr_title": "What you'll do",
        "instr_p1": "Imagine you are at work. For each of 14 short tasks, a coworker asks for something and an <b>AI assistant</b> gives an answer.",
        "instr_multi": "For some tasks you'll see the answer from <b>one</b> AI model; for others, <b>five</b> different AI models were each asked and all five gave the same answer.",
        "instr_p2": "Your only job each time is to decide <b>one thing</b>:",
        "instr_opt1": "<b>✅ The answer is ready to use</b> — nothing important is left unclear.",
        "instr_opt2": "<b>⚠️ Important information is missing</b> — you'd need to clarify something before trusting it.",
        "instr_p3": "If you choose “missing,” we'll ask which one thing you would clarify. Then you rate how confident you are that the answer is correct. That's it — let's try one example first.",
        "we_title": "Example (not scored)",
        "we_scenario": "A coworker says: “Book a meeting room for the team next Friday at 10.”",
        "we_task": "Book the room.",
        "we_answer": "Booked Room A for next Friday at 10 AM.",
        "we_explain": "The AI <b>assumed</b> 10 in the morning — but the request only said “10,” never morning or evening. When a needed detail like that is missing, the answer might be wrong, and you'd clarify first. When nothing important is missing, the answer is fine to use as-is.",
        "we_ready": "Ready — you'll now do 14 short tasks. <b>Some answers will be fine to use as-is; others may be missing a needed detail.</b> Read each one and decide.",
        "comp_title": "Quick check",
        "comp_q": "In each task, your job is to decide:",
        "comp_o0": "Whether the answer is written politely",
        "comp_o1": "Whether the answer is ready to use, or important information is missing",
        "comp_o2": "How quickly the AI responded",
        "comp_err": "Not quite — please re-read the short instructions and try again.",
        "trial_progress": "Task {n} of {total}",
        "lbl_scenario": "The situation",
        "lbl_task": "What's being asked",
        "lbl_answer_single": "1 AI model was asked:",
        "lbl_answer_multi": "5 AI models were asked — all 5 gave the same answer:",
        "banner_fake": "ℹ️ Five different AI models were each asked, and all five gave this answer.",
        "banner_dep": "ℹ️ All five models were sent the <b>same prompt</b>, and that prompt did not specify one needed detail — each model filled that gap on its own.",
        "q1": "Is this answer ready to use, or is important information missing?",
        "a_accept": "✅ Ready to use as-is",
        "a_flag": "⚠️ Important information is missing — I'd clarify first",
        "gap_q": "You said something's missing. What is the <b>most important</b> thing to clarify?",
        "conf_q": "How confident are you that this answer is correct?",
        "conf_star_hint": "(1 star = not at all sure, 5 stars = completely sure)",
        "err_need_choice": "Please choose one option above to continue.",
        "err_need_gap": "Please pick the most important thing to clarify.",
        "err_need_conf": "Please give a star rating.",
        "attn_title": "Attention check",
        "attn_q": "To show you are reading, please choose <b>Disagree</b> below.",
        "attn_a1": "Agree",
        "attn_a0": "Disagree",
        "attn_a2": "Neutral",
        "demo_title": "A few last questions",
        "demo_age": "Your age group",
        "age_groups": [
            "Under 18",
            "18–24",
            "25–34",
            "35–44",
            "45–54",
            "55–64",
            "65+"
        ],
        "demo_ai_q": "How often do you use AI assistants (e.g., ChatGPT)?",
        "demo_ai": [
            "Never",
            "Rarely",
            "Sometimes",
            "Often",
            "Daily"
        ],
        "debrief_title": "Thank you — what this study was really about",
        "debrief_p1": "The AI answers, and especially the <b>“5 of 5 AI models agree”</b> displays, were <b>examples created by the researchers</b> — not live outputs from real models. Each task was also <b>deliberately left underspecified</b>: it dropped one detail (for example, whether “Q1” follows a calendar or fiscal year) needed to be sure the answer is right. So in every task, the appropriate response was to notice that important information was missing.",
        "debrief_p2": "We study whether a unanimous “models agree” display makes people more likely to accept an answer and feel more confident, and whether telling people the answers are not independent helps. Different people saw the same tasks with different displays, so we can compare fairly.",
        "finish": "Submit and finish"
    },
    "zh": {
        "next": "继续",
        "consent_title": "看懂 AI 助手的回答",
        "consent_p1": "诚邀您参加一项约 10 分钟的短研究，关于人们如何阅读 AI 助手的回答。您会看 14 个短小的工作场景，每个做一个快速判断和一个评分。",
        "consent_p2": "为了让回答更自然，研究的确切目的有一部分暂时不告知，会在结束时完整说明。除普通上网外无任何风险。参与自愿、匹名，可随时关闭窗口退出。完成后发放报酬。",
        "consent_agree": "我已阅读上述内容，并同意参与。",
        "instr_title": "您要做什么",
        "instr_p1": "想象您在上班。在 14 个短任务中，同事提出一个请求，一个 <b>AI 助手</b> 给出回答。",
        "instr_multi": "有的题您会看到<b>一个</b> AI 模型的回答；有的题是<b>五个</b>不同的 AI 模型各自作答，五个都给出了同一个答案。",
        "instr_p2": "每次您只需判断<b>一件事</b>：",
        "instr_opt1": "<b>✅ 这个回答可以直接用</b> — 没有重要的地方含糊不清。",
        "instr_opt2": "<b>⚠️ 缺了重要信息</b> — 你得先濄清某个点才能信任它。",
        "instr_p3": "如果选“缺信息”，我们会问您最想濄清哪一点。然后您为这个回答有多大把握评分。就这些 — 先试一个例子。",
        "we_title": "示范题（不计分）",
        "we_scenario": "同事说：“帮团队订下周五 10 点的会议室。”",
        "we_task": "订会议室。",
        "we_answer": "已订下周五上午 10:00 的 A 会议室。",
        "we_explain": "AI <b>擅自默认</b>了上午，但请求只说了“10 点”，没说上午还是晚上。当这样一个需要的细节缺失时，回答可能是错的，你会先去濄清；而当没有重要信息缺失时，回答就可以直接用。",
        "we_ready": "准备好了 — 接下来您会做 14 个短任务。<b>有的回答可以直接用，有的可能缺了一个需要的细节。</b>认真读每一题再判断。",
        "comp_title": "小测一下",
        "comp_q": "在每个任务中，您的任务是判断：",
        "comp_o0": "回答写得礼不礼貌",
        "comp_o1": "回答可不可以直接用，还是缺了重要信息",
        "comp_o2": "AI 回应有多快",
        "comp_err": "不太对 — 请重读一下说明再试。",
        "trial_progress": "第 {n} / {total} 题",
        "lbl_scenario": "情境",
        "lbl_task": "要求",
        "lbl_answer_single": "询问了 1 个 AI 模型：",
        "lbl_answer_multi": "询问了 5 个 AI 模型 — 5 个都给出了同一个答案：",
        "banner_fake": "ℹ️ 五个不同的 AI 模型各自分别被询问，五个都给出了这个答案。",
        "banner_dep": "ℹ️ 五个模型收到的是<b>同一条 prompt</b>，而这条 prompt 没有说清其中一个需要的细节 — 五个模型各自把这个空填上了。",
        "q1": "这个回答可以直接用，还是缺了重要信息？",
        "a_accept": "✅ 可以直接用",
        "a_flag": "⚠️ 缺了重要信息 — 我会先去濄清",
        "gap_q": "您说缺了东西。<b>最需要</b>先濄清的是哪一点？",
        "conf_q": "您有多确信这个回答是对的？",
        "conf_star_hint": "（1 星 = 完全不确信，5 星 = 完全确信）",
        "err_need_choice": "请先选择上面一项再继续。",
        "err_need_gap": "请选出最需要濄清的一点。",
        "err_need_conf": "请给出星级评分。",
        "attn_title": "注意力检查",
        "attn_q": "为表明您在认真阅读，请选择下面的<b>不同意</b>。",
        "attn_a1": "同意",
        "attn_a0": "不同意",
        "attn_a2": "中立",
        "demo_title": "最后几个问题",
        "demo_age": "你的年龄段",
        "age_groups": [
            "18 岁以下",
            "18–24",
            "25–34",
            "35–44",
            "45–54",
            "55–64",
            "65 岁以上"
        ],
        "demo_ai_q": "您多常使用 AI 助手（如 ChatGPT）？",
        "demo_ai": [
            "从不",
            "很少",
            "有时",
            "经常",
            "每天"
        ],
        "debrief_title": "谢谢 — 这项研究的真正目的",
        "debrief_p1": "这些 AI 回答，尤其是<b>“5 个 AI 模型中 5 个一致”</b>的显示，都是<b>研究者构造的示例</b> — 并非真实模型的实时输出。每个任务也是<b>故意留不完整的</b>：它省去了一个确定答案所需的细节（比如“Q1”按日历年还是财年）。所以每题的恰当反应都是注意到缺了重要信息。",
        "debrief_p2": "我们研究：“多模型一致”的显示是否会让人更容易接受答案、更有把握；以及告知“这些答案并不独立”是否有帮助。不同的人看到的是同样题目的不同显示，以便公平比较。",
        "finish": "提交并结束"
    }
}

assert set(UI["en"].keys()) == set(UI["zh"].keys()), "en/zh UI keys out of sync"
