# 12 audited items (from STIMULI-v2.md). ASCII-safe. options[0] is always the GOLD
# (decisive) clarifying question; the other three are cosmetic/non-decisive distractors.
# At runtime the four options are shuffled per trial (see __init__.creating_session).

ITEMS = [
    dict(id="01", conv="fiscal-year start",
         scenario='A colleague messages before leave: "Pull our Q1 revenue for the board deck."',
         task="Report Q1 revenue.",
         answer="Q1 revenue (January-March) was $2.4M.",
         gold="Which months count as Q1 - does the fiscal year start in January or another month?",
         distractors=["Should the number be rounded to the nearest $10,000?",
                      "Should the answer use a dollar sign?",
                      "Should the deck use a chart or a table?"]),
    dict(id="02", conv="rounding/remainder",
         scenario='Handoff note: "Split the $100.00 bonus pool equally among the 3 and tell me each amount."',
         task="Give each person's amount.",
         answer="Each person gets $33.33.",
         gold="How should the leftover cent be handled - round each share, or give the remainder to one person?",
         distractors=["Should the amounts be listed or written in a sentence?",
                      "Should each amount include a dollar sign?",
                      "Should the names be listed alphabetically?"]),
    dict(id="03", conv="inclusive/exclusive range",
         scenario='"Give me total sales for the first week of March (March 1 to March 7)."',
         task="Total sales for that range.",
         answer="Total sales March 1-7 were $18,200.",
         gold="Is March 7 itself included, or does the range stop at the end of March 6?",
         distractors=["Should the total be rounded to the nearest $100?",
                      "Should the answer include a dollar sign?",
                      "Should the answer be a sentence or a table?"]),
    dict(id="04", conv="dedup",
         scenario='"How many unique customers did we serve last month? Here is the order log."',
         task="Count unique customers.",
         answer="You served 1,240 unique customers last month.",
         gold="What identifies a unique customer - email, name, or name+phone?",
         distractors=["Should the count be rounded to a whole number?",
                      "Should the answer say 'customers' or 'people'?",
                      "Should the answer be a sentence or a table?"]),
    dict(id="05", conv="top-N tie",
         scenario='"Send me the top 10 sales reps by revenue this quarter." (reps ranked 10 and 11 are tied)',
         task="List the top 10.",
         answer="Here are the top 10 reps [list].",
         gold="Two reps are tied at #10 - include both, or exactly ten names?",
         distractors=["Should the names be numbered?",
                      "Should the list be alphabetical or by rank?",
                      "Should the list be sent by email or chat?"]),
    dict(id="06", conv="timezone",
         scenario='"How many orders came in before midnight on Friday?"',
         task="Count Friday's pre-midnight orders.",
         answer="312 orders came in before midnight Friday.",
         gold='"Before midnight Friday" in which timezone - UTC/server time or local time?',
         distractors=["Should the count be rounded to a whole number?",
                      "Should the answer say 'orders' or 'purchases'?",
                      "Should the answer be a full sentence?"]),
    dict(id="07", conv="unit/scale",
         scenario='A budget tracker shows this team\'s budget as "5"; the unit label (dollars, or thousands of dollars) is missing. "Is our $4,200 spend within budget?"',
         task="Say whether spend is within budget.",
         answer="Yes - $4,200 is within the $5,000 budget.",
         gold='Is the budget "5" in dollars, or in thousands of dollars?',
         distractors=["Should the answer include a dollar sign?",
                      "Should the answer be a full sentence?",
                      "Should the result be bolded?"]),
    dict(id="08", conv="percentage base",
         scenario='"Customer satisfaction was 60% last month. A report says it \'increased 20%\' this month. What is this month\'s score?"',
         task="Report this month's score.",
         answer="Satisfaction is now 80%.",
         gold='Does "increased 20%" mean 20 percentage points, or a 20% rise from 60%?',
         distractors=["Should the answer include the word 'satisfaction'?",
                      "Should the answer be rounded to a whole percent?",
                      "Should the result be shown in bold?"]),
    dict(id="09", conv="mean vs median",
         scenario='"What is the average response time for support tickets this week?" (a few took hours; most took minutes)',
         task="Report the average.",
         answer="The average response time was 47 minutes.",
         gold='By "average" do you want the mean or the median - a few long tickets skew the mean?',
         distractors=["Should the answer be rounded to whole minutes?",
                      "Should the answer include the word 'minutes'?",
                      "Should the answer be a sentence or a table?"]),
    dict(id="10", conv="business vs calendar days",
         scenario='"The SLA says reply within 2 days. A ticket arrived Friday 4pm. When is it due?"',
         task="Give the due time.",
         answer="It is due by Sunday 4pm.",
         gold='Does "2 days" mean calendar days or business days (excluding the weekend)?',
         distractors=["Should the due time be written with 'am' or 'pm'?",
                      "Should the answer include the weekday name?",
                      "Should the answer be a full sentence?"]),
    dict(id="11", conv="sort tie-break",
         scenario='"Rank these regions by growth and tell me who is #1." (two regions are tied on growth)',
         task="Name the #1 region.",
         answer="North is #1 by growth.",
         gold="North and West are tied on growth - how should the tie be broken (e.g., by revenue)?",
         distractors=["Should the answer include both region names?",
                      "Should we show percentages or ranks?",
                      "Should the answer be presented in bold?"]),
    dict(id="12", conv="null/blank handling",
         scenario='"What is the average satisfaction score from this survey?" (several respondents left it blank)',
         task="Report the average score.",
         answer="The average satisfaction score was 4.1 out of 5.",
         gold="Should blank scores be left out of the average, or counted as zero?",
         distractors=["Should the answer be rounded to one decimal place?",
                      "Should the answer include 'out of 5'?",
                      "Should the answer be a sentence or a table?"]),
]

assert len(ITEMS) == 12
