# -*- coding: utf-8 -*-
"""Items for the human-reliance study, bilingual (en/zh).

`complete` marks whether the task is fully specified:
  - complete=False (underspecified): the answer silently commits to one value of an UNSTATED
    convention; the appropriate response is FLAG. `gold` = the decisive clarifying question
    (index 0 of [gold]+distractors); the 3 distractors are non-decisive.
  - complete=True (well-specified): the convention IS stated, so the answer is correct and the
    appropriate response is ACCEPT. `gold` is None (gap-ID not scored); options are generic.

The completeness factor (crossed with display condition) drives the PRIMARY discrimination DV:
does displayed consensus reduce a participant's accept-gap between complete and underspecified
items (i.e., degrade their ability to notice missing information)? This mirrors the paper's
within-item k=0 (convention retained) vs k>=1 (convention deleted) control.

Answers are stripped of any text that would self-disclose the missing convention.
Option order is shuffled per trial at runtime (see __init__.creating_session).
"""

# generic, non-decisive clarifying options for COMPLETE items (gold=None)
_GEN = {
    "en": ["Should the answer include units?", "Should it be a number or a full sentence?",
           "Should it be rounded?", "Should the result be bolded?"],
    "zh": ["答案要带单位吗?", "写成数字还是完整句子?", "要四舍五入吗?", "结果要加粗吗?"],
}

ITEMS = [
    # ---------------------------------------------------------------- UNDERSPECIFIED (9) ----
    dict(id="U1", conv="fiscal-year start", complete=False,
         scenario={"en": 'A coworker messages before leave: "Pull our Q1 revenue for the board deck."',
                   "zh": '同事休假前留言:"帮我拉一下我们的 Q1 营收,放进给董事会的材料里。"'},
         task={"en": "Report Q1 revenue.", "zh": "报告 Q1 营收。"},
         answer={"en": "Q1 revenue was $2.4M.", "zh": "Q1 营收为 240 万美元。"},
         gold={"en": "Which months count as Q1 - does the fiscal year start in January or another month?",
               "zh": "Q1 指哪几个月——财年是从 1 月开始,还是别的月份?"},
         distractors={"en": ["Should the number be rounded to the nearest $10,000?",
                             "Should the answer use a dollar sign?",
                             "Should the deck use a chart or a table?"],
                      "zh": ["营收数字要四舍五入到最近的 1 万美元吗?", "答案里要带美元符号吗?",
                             "材料里用图表还是表格?"]}),
    dict(id="U2", conv="rounding/remainder", complete=False,
         scenario={"en": 'Handoff note: "Split the $100.00 bonus pool equally among the 3 and tell me each amount."',
                   "zh": '交接便条:"把 100.00 美元的奖金池在 3 个人之间平均分,把每人金额告诉我。"'},
         task={"en": "Give each person's amount.", "zh": "给出每人金额。"},
         answer={"en": "Each person gets $33.33.", "zh": "每人分得 33.33 美元。"},
         gold={"en": "How should the leftover cent be handled - round each share, or give the remainder to one person?",
               "zh": "多出来的那一分钱怎么处理——每份四舍五入,还是把余数给某一个人?"},
         distractors={"en": ["Should the amounts be listed or written in a sentence?",
                             "Should each amount include a dollar sign?",
                             "Should the names be listed alphabetically?"],
                      "zh": ["金额要列成清单还是写成一句话?", "每个金额要带美元符号吗?",
                             "名字要按字母顺序排列吗?"]}),
    dict(id="U3", conv="inclusive/exclusive range", complete=False,
         scenario={"en": '"Give me total sales for the first week of March (March 1 to March 7)."',
                   "zh": '"给我三月第一周(3 月 1 日到 3 月 7 日)的销售总额。"'},
         task={"en": "Total sales for that range.", "zh": "该区间的销售总额。"},
         answer={"en": "Total sales for that week were $18,200.", "zh": "那一周的销售总额为 18,200 美元。"},
         gold={"en": "Is March 7 itself included, or does the range stop at the end of March 6?",
               "zh": "3 月 7 日当天算在内,还是到 3 月 6 日结束为止?"},
         distractors={"en": ["Should the total be rounded to the nearest $100?",
                             "Should the answer include a dollar sign?",
                             "Should the answer be a sentence or a table?"],
                      "zh": ["总额要四舍五入到最近的 100 美元吗?", "答案要带美元符号吗?",
                             "答案写成一句话还是表格?"]}),
    dict(id="U4", conv="dedup", complete=False,
         scenario={"en": '"How many unique customers did we serve last month? Here is the order log."',
                   "zh": '"上个月我们服务了多少位独立客户?这是订单日志。"'},
         task={"en": "Count unique customers.", "zh": "统计独立客户数。"},
         answer={"en": "You served 1,240 unique customers last month.", "zh": "上个月你服务了 1,240 位独立客户。"},
         gold={"en": "What identifies a unique customer - email, name, or name+phone?",
               "zh": "什么算一位独立客户——按邮箱、按姓名,还是按姓名+电话?"},
         distractors={"en": ["Should the count be rounded to a whole number?",
                             "Should the answer say 'customers' or 'people'?",
                             "Should the answer be a sentence or a table?"],
                      "zh": ["数字要取整到整数吗?", "答案说'客户'还是'人'?", "答案写成一句话还是表格?"]}),
    dict(id="U5", conv="timezone", complete=False,
         scenario={"en": '"How many orders came in before midnight on Friday?"',
                   "zh": '"周五午夜之前有多少笔订单?"'},
         task={"en": "Count Friday's pre-midnight orders.", "zh": "统计周五午夜前的订单。"},
         answer={"en": "312 orders came in before midnight Friday.", "zh": "周五午夜前有 312 笔订单。"},
         gold={"en": '"Before midnight Friday" in which timezone - UTC/server time or local time?',
               "zh": "'周五午夜之前'按哪个时区——UTC/服务器时间还是本地时间?"},
         distractors={"en": ["Should the count be rounded to a whole number?",
                             "Should the answer say 'orders' or 'purchases'?",
                             "Should the answer be a full sentence?"],
                      "zh": ["数字要取整到整数吗?", "答案说'订单'还是'购买'?", "答案要写成完整句子吗?"]}),
    dict(id="U6", conv="percentage base", complete=False,
         scenario={"en": '"Customer satisfaction was 60% last month. A report says it \'increased 20%\' this month. What is this month\'s score?"',
                   "zh": '"上个月客户满意度是 60%。一份报告说这个月\'提高了 20%\'。这个月是多少?"'},
         task={"en": "Report this month's score.", "zh": "报告这个月的分数。"},
         answer={"en": "Satisfaction is now 80%.", "zh": "满意度现在是 80%。"},
         gold={"en": 'Does "increased 20%" mean 20 percentage points, or a 20% rise from 60%?',
               "zh": "'提高了 20%' 指提高 20 个百分点,还是在 60% 基础上相对提高 20%?"},
         distractors={"en": ["Should the answer include the word 'satisfaction'?",
                             "Should the answer be rounded to a whole percent?",
                             "Should the result be shown in bold?"],
                      "zh": ["答案里要带'满意度'这个词吗?", "答案要取整到整数百分比吗?", "结果要加粗显示吗?"]}),
    dict(id="U7", conv="mean vs median", complete=False,
         scenario={"en": '"What is the average response time for support tickets this week?" (a few took hours; most took minutes)',
                   "zh": '"这周工单的平均响应时间是多少?"(少数几单花了几小时,多数只要几分钟)'},
         task={"en": "Report the average.", "zh": "报告平均值。"},
         answer={"en": "The average response time was 47 minutes.", "zh": "平均响应时间为 47 分钟。"},
         gold={"en": 'By "average" do you want the mean or the median - a few long tickets skew the mean?',
               "zh": "'平均'你要的是均值还是中位数——少数长工单会把均值拉高?"},
         distractors={"en": ["Should the answer be rounded to whole minutes?",
                             "Should the answer include the word 'minutes'?",
                             "Should the answer be a sentence or a table?"],
                      "zh": ["答案要取整到整分钟吗?", "答案里要带'分钟'这个词吗?", "答案写成一句话还是表格?"]}),
    dict(id="U8", conv="business vs calendar days", complete=False,
         scenario={"en": '"The SLA says reply within 2 days. A ticket arrived Friday 4pm. When is it due?"',
                   "zh": '"SLA 规定 2 天内回复。一个工单周五下午 4 点到达。什么时候到期?"'},
         task={"en": "Give the due time.", "zh": "给出到期时间。"},
         answer={"en": "It is due by Sunday 4pm.", "zh": "到期时间是周日下午 4 点。"},
         gold={"en": 'Does "2 days" mean calendar days or business days (excluding the weekend)?',
               "zh": "'2 天'指日历日还是工作日(不含周末)?"},
         distractors={"en": ["Should the due time be written with 'am' or 'pm'?",
                             "Should the answer include the weekday name?",
                             "Should the answer be a full sentence?"],
                      "zh": ["到期时间用'上午/下午'怎么写?", "答案要带星期几吗?", "答案要写成完整句子吗?"]}),
    dict(id="U9", conv="null/blank handling", complete=False,
         scenario={"en": '"What is the average satisfaction score from this survey?" (several respondents left it blank)',
                   "zh": '"这份问卷的平均满意度分是多少?"(有几位受访者没填分数)'},
         task={"en": "Report the average score.", "zh": "报告平均分。"},
         answer={"en": "The average satisfaction score was 4.1 out of 5.", "zh": "平均满意度为 4.1 分(满分 5)。"},
         gold={"en": "Should blank scores be left out of the average, or counted as zero?",
               "zh": "空白的分数是从平均里剔除,还是按 0 分计?"},
         distractors={"en": ["Should the answer be rounded to one decimal place?",
                             "Should the answer include 'out of 5'?",
                             "Should the answer be a sentence or a table?"],
                      "zh": ["答案要取整到一位小数吗?", "答案要带'满分 5'吗?", "答案写成一句话还是表格?"]}),
    # ---------------------------------------------------------------- COMPLETE (5) ----------
    # Well-specified twins: the convention is STATED, so the answer is correct -> ACCEPT.
    dict(id="C1", conv="fiscal-year start (stated)", complete=True,
         scenario={"en": 'A coworker: "Reminder - our fiscal year starts in January. Which months are Q1?"',
                   "zh": '同事:"提醒一下——我们的财年从 1 月开始。Q1 是哪几个月?"'},
         task={"en": "Name the Q1 months.", "zh": "说出 Q1 是哪几个月。"},
         answer={"en": "Q1 is January, February, and March.", "zh": "Q1 是 1 月、2 月、3 月。"},
         gold=None, distractors=_GEN),
    dict(id="C2", conv="inclusive range (stated)", complete=True,
         scenario={"en": '"Count the days from March 1 to March 5, including both March 1 and March 5."',
                   "zh": '"数一下从 3 月 1 日到 3 月 5 日一共多少天,3 月 1 日和 3 月 5 日都算在内。"'},
         task={"en": "Give the number of days.", "zh": "给出天数。"},
         answer={"en": "That is 5 days.", "zh": "一共 5 天。"},
         gold=None, distractors=_GEN),
    dict(id="C3", conv="rounding (stated)", complete=True,
         scenario={"en": '"Split a $60 gift card equally among 4 people - it divides evenly. How much each?"',
                   "zh": '"把一张 60 美元的礼品卡在 4 个人之间平均分——正好整除。每人多少?"'},
         task={"en": "Give each person's amount.", "zh": "给出每人金额。"},
         answer={"en": "Each person gets $15.", "zh": "每人分得 15 美元。"},
         gold=None, distractors=_GEN),
    dict(id="C4", conv="calendar days (stated)", complete=True,
         scenario={"en": '"Deliver within 2 calendar days. An order shipped on Monday - when does it arrive?"',
                   "zh": '"2 个自然日内送达。一个订单周一发货——什么时候到?"'},
         task={"en": "Give the arrival day.", "zh": "给出到达日。"},
         answer={"en": "It arrives on Wednesday.", "zh": "周三到达。"},
         gold=None, distractors=_GEN),
    dict(id="C5", conv="median (stated)", complete=True,
         scenario={"en": '"What is the median response time this week? The middle value is 9 minutes."',
                   "zh": '"这周响应时间的中位数是多少?中间值是 9 分钟。"'},
         task={"en": "Report the median.", "zh": "报告中位数。"},
         answer={"en": "The median response time is 9 minutes.", "zh": "响应时间的中位数是 9 分钟。"},
         gold=None, distractors=_GEN),
]

N_UNDERSPECIFIED = sum(1 for it in ITEMS if not it["complete"])
N_COMPLETE = sum(1 for it in ITEMS if it["complete"])
assert len(ITEMS) == 14 and N_UNDERSPECIFIED == 9 and N_COMPLETE == 5
